name: lateDiary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
#  location: ^4.4.0
  path_provider:
  cupertino_icons: ^1.0.2
#  record: ^4.3.1
#  sensors_plus: ^1.3.2
#  flutter_sensors:
  graphic:
  df:
  intl: ^0.17.0
  ml_dataframe: ^1.6.0
  image: ^3.2.0
  flutter_logs:
  permission_handler:
  matrix2d:
  fluttertoast: ^8.0.9
  settings_ui:
  glob:
  provider: ^6.0.4
  matrix_gesture_detector: ^0.1.0
  animations:
  transparent_image:
  extended_image:
  exif:
  image_picker:
  badges:
  geolocator:
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.5
  flutter_keyboard_visibility: ^5.4.0
  flutter_keyboard_size:
  flutter_native_splash:
  external_path:
  url_launcher:
  flutter_shake_animated:
  numberpicker:
  photo_manager:
  go_router:
  flutter_animated_button:
  dropdown_button2:
  photo_view:
  clickable_list_wheel_view:
  scidart:
  screenshot:
  share_plus: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
    #    android_12:
  flutter_lints: ^2.0.0






flutter_native_splash:
  image: images/playstore.png
  color: "#ffffff"
#  android_12:
#    image: images/test.png
#    color: "#f56f42"
#    icon_background_color: "#eeeeee"


#    android: true
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:

    - family: NotoSansKR
      fonts:
      - asset: assets/font/NotoSansKR-Light.otf
        weight: 300
      - asset: assets/font/NotoSansKR-Regular.otf
        weight: 400
      - asset: assets/font/NotoSansKR-Medium.otf
        weight: 500
      - asset: assets/font/NotoSansKR-Bold.otf
        weight: 700
      - asset: assets/font/NotoSansKR-Black.otf
        weight: 900

    - family: NotoSans
      fonts:
      - asset : assets/font/NotoSans-ExtraLight.ttf
        weight: 200
      - asset: assets/font/NotoSans-Light.ttf
        weight: 300
      - asset: assets/font/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/font/NotoSans-Medium.ttf
        weight: 500
      - asset: assets/font/NotoSans-Semibold.ttf
        weight: 600
      - asset: assets/font/NotoSans-Bold.ttf
        weight: 700
      - asset: assets/font/NotoSans-Black.ttf
        weight: 900

  #   - images/a_dot_ham.jpeg

