name: jjuma.d
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider: 2.0.11
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  image: ^3.2.0
  flutter_logs: 2.1.10
  permission_handler: 10.2.0
  matrix2d: ^1.0.3
  settings_ui: ^2.0.2
  glob: ^2.1.1
  provider: ^6.0.4
  animations: ^2.0.7
  extended_image: ^6.3.4
  exif: ^3.1.2
  flutter_native_splash: ^2.2.16
  external_path: ^1.0.3
  url_launcher: ^6.1.7
  flutter_shake_animated: ^0.0.5
  photo_manager: ^2.5.2
  go_router: ^6.0.0
  dropdown_button2: ^1.9.2
  photo_view: ^0.14.0
  clickable_list_wheel_view: ^0.2.0
  scidart: ^0.0.2-dev.12
  screenshot: ^1.3.0
  share_plus: 6.3.0
  csv: ^5.0.1
  swipeable_page_route: ^0.2.6
  ml_algo: 16.17.7
  simple_cluster: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
    #    android_12:
  flutter_lints: ^2.0.0


flutter_native_splash:
  image: images/playstore.png
  color: "#2A2A2A"
#  android_12:
#    image: images/test.png
#    color: "#f56f42"
#    icon_background_color: "#eeeeee"


#    android: true
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:

    - family: NotoSansKR
      fonts:
      - asset: assets/font/NotoSansKR-Light.otf
        weight: 300
      - asset: assets/font/NotoSansKR-Regular.otf
        weight: 400
      - asset: assets/font/NotoSansKR-Medium.otf
        weight: 500
      - asset: assets/font/NotoSansKR-Bold.otf
        weight: 700
      - asset: assets/font/NotoSansKR-Black.otf
        weight: 900

    - family: NotoSans
      fonts:
      - asset : assets/font/NotoSans-ExtraLight.ttf
        weight: 200
      - asset: assets/font/NotoSans-Light.ttf
        weight: 300
      - asset: assets/font/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/font/NotoSans-Medium.ttf
        weight: 500
      - asset: assets/font/NotoSans-Semibold.ttf
        weight: 600
      - asset: assets/font/NotoSans-Bold.ttf
        weight: 700
      - asset: assets/font/NotoSans-Black.ttf
        weight: 900

  #   - images/a_dot_ham.jpeg

